### ISSUE TITLE
没有实现监听功能啊

### ISSUE THREAD

**Issue by AndyUkJ** [XTShow/XTVolumeMonitor#1]
开启app
切换静音键,打开或者关闭,没有任何方法火车block响应啊.

**Comment by XTShow** [comment]
@huaweiluo 这个没有实现主动回调，而是在需要的时候我们手动调用，返回静音状态；如果需要主动回调的话，可以做个轮询，里面调用我这里面的方法，在值change的时候向外回调，也算是一种主动回调的模拟实现吧~

**Comment by AndyUkJ** [comment]
只能是轮询了，否则在一个页面。用户手动切换按钮了，你是检测不到的。
